const colors = {
  light: {
    text: "#FFFFFF",
    tint: "#00D4FF",
    background: "#08081A",
    foreground: "#FFFFFF",
    card: "#0F0F28",
    cardForeground: "#FFFFFF",
    primary: "#00D4FF",
    primaryForeground: "#08081A",
    secondary: "#141435",
    secondaryForeground: "#B0B0D0",
    muted: "#1C1C3A",
    mutedForeground: "#6B6B9A",
    accent: "#FF2D78",
    accentForeground: "#FFFFFF",
    destructive: "#FF4B4B",
    destructiveForeground: "#FFFFFF",
    border: "#252550",
    input: "#1C1C3A",
    success: "#00E5A0",
    warning: "#FFB800",
    gold: "#FFD700",
    purple: "#7B2FBE",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#00D4FF",
    background: "#08081A",
    foreground: "#FFFFFF",
    card: "#0F0F28",
    cardForeground: "#FFFFFF",
    primary: "#00D4FF",
    primaryForeground: "#08081A",
    secondary: "#141435",
    secondaryForeground: "#B0B0D0",
    muted: "#1C1C3A",
    mutedForeground: "#6B6B9A",
    accent: "#FF2D78",
    accentForeground: "#FFFFFF",
    destructive: "#FF4B4B",
    destructiveForeground: "#FFFFFF",
    border: "#252550",
    input: "#1C1C3A",
    success: "#00E5A0",
    warning: "#FFB800",
    gold: "#FFD700",
    purple: "#7B2FBE",
  },
  radius: 20,
};

export default colors;
